# Generated by Django 3.1 on 2020-09-06 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200904_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='company',
        ),
    ]
